---
- name: Install Jenkins
  hosts: localhost
  become: yes
  
  tasks:
  - name: Download apt key for Jenkins
    ansible.builtin.apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present
  - name: Add Jenkins to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://pkg.jenkins.io/debian-stable binary/
      state: present
      filename: jenkins
  - name: Update apt cache and install Jenkins
    ansible.builtin.apt:
      name: jenkins
      update_cache: yes
  - name: Ensure Jenkins started and enabled
    ansible.builtin.systemd:
      name: jenkins
      enabled: true
      state: started